import Head from "next/head";
import Image from "next/image";
import Header from "../Components/Header";
import Movies from "../Components/Movies";
import NavBar from "../Components/NavBar";
import requests from "../utils/requests";

export default function Home({ results }) {
    return (
        <div className="h-full w-full ">
            <Head>
                <title>Hulu Clone by Vivek</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <NavBar />

            <Movies results={results} />
        </div>
    );
}

export async function getServerSideProps(context) {
    const genre = context.query.genre;

    const request = await fetch(
        `https://api.themoviedb.org/3${
            requests[genre]?.url || requests.fetchTrending.url
        } `
    )
        .then((res) => res.json())
        .catch((error) => {
            console.log(error.message);
        });
    return {
        props: {
            results: request?.results,
        },
    };
}
